version: '3.8'

services:
  postgres:
    image: postgres:14.5
    container_name: diagrams_core_db
    restart: always
    env_file:
      - ./.env.docker
    ports:
      - 5432:5432

  app:
    image: node:16.15
    env_file:
      - ./.env.docker
    container_name: diagrams_core_app
    restart: on-failure:10
    depends_on:
      - postgres
    ports:
      - 5001:5001
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    command: bash -c "npm install && npm run migrations && npm run seeds && npm run test"
